### ISSUE TITLE
Input point cloud has no data

### ISSUE THREAD

**Issue by edwincasallas22** [danielTobon43/pointcloudToPCD#1]
Hello
When I try to work with this code I get the following error:
`terminate called after throwing an instance of 'pcl::IOException' what(): : [pcl::PCDWriter::writeBinary] Input point cloud has no data!`

You could help me?

**Comment by ghost** [comment]
Could you provide me the input file that are you using and the command line? it seems a problem of argv but I will check

**Comment by edwincasallas22** [comment]
This is my input file [1.txt](https://github.com/danielTobon43/pointcloudToPCD/files/3941463/1.txt)
the command line that I'm using is: ./pointcloudToPCD 1.txt -o myFolder
Thanks for your answer

**Comment by ghost** [comment]
Ok, the problem is the input file. You have in your 1.txt: `%X  Y	Z	R	G`. The code to read the input file doesn't accept that line, just numbers. You have to delete that line, something like:
```

2.11428689957	3.82100009918	1.56115150452	97	80	74
-2.1070086956	3.82100009918	1.56115150452	96	81	76
-2.09973073006	3.82100009918	1.56115150452	95	82	72
-2.09245252609	3.82100009918	1.56115150452	94	82	67
-2.08517432213	3.82100009918	1.56115150452	94	81	65
-2.05505633354	3.77900028229	1.5439915657	86	77	63
-2.07061815262	3.82100009918	1.56115150452	79	71	49
```

**Comment by edwincasallas22** [comment]
Thank you very much!!
I have another question, when I try to convert my .txt file with XYZRGB information to a .PCD file, my point cloud loses its natural colors. You know why?

**Comment by ghost** [comment]
Show me a picture from the original pointcloud I will check about the color format

**Comment by ghost** [comment]
Ok, the color is a problem that I thought I changed before. I will update the main.cpp with the correction.

**Comment by ghost** [comment]
Download the new update on the repo, compile it and try it again. I hope to help you.

**Comment by thisisjaskaran** [comment]
@edwincasallas22 did you get this error which executing the launch file?
if so, could you please guide me as to whether i need to download a dataset for the tutorial given [here](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM)? When I roslaunch, I'm shown the same error as the name of this issue and rviz shows a black screen.
